parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 6
  project: "tsconfig.json"

env:
  browser: true

extends:
  - plugin:@typescript-eslint/recommended
  - prettier

plugins:
  - prettier

rules:
  prettier/prettier: error
  no-bitwise: ['error', { 'allow': ['~'] }]
  no-alert: 0
  no-console: 0
  object-curly-newline: 0
  no-nested-ternary: 0
  '@typescript-eslint/object-curly-spacing': 0
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/no-non-null-assertion': off
