service: serverless-api

# Create an optimized package for our functions
package:
  individually: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline # Emulate AWS lamda and API Gateway on local machine
  - serverless-dotenv-plugin # Load .env as environment variables

useDotenv: true

custom:
  bundle:
    linting: true

functions:
  setup:
    handler: setup.status
    events:
      - http:
          path: setup
          method: get
